<?php

namespace Database\Seeders;

use App\Models\Company\Booking;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BookingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $bookings = [
            [
                'insurance_id' => 1,
                'booking_code' => 10000001,
                'first_name' => 'John',
                'last_name' => 'Doe',
                'birthday' => '1990-01-01',
                'email' => 'john@example.com',
                'phone' => '+355111111111',
                'additional_phone' => null,
                'days' => 1,
                'daily_rate' => 40,
                'total_price' => 40,
                'addons_total' => 0,
                'pickup_date' => '2026-01-12',
                'dropoff_date' => '2026-01-13',
                'pickup_time' => '10:00:00',
                'dropoff_time' => '09:00:00',
                'ways_of_contact' => 1,
                'vehicle_id' => 1,
                'company_id' => 1,
                'pickup_location' => 1,
                'dropoff_location' => 1,
                'booking_status_id' => 4,
                'cancelled_at' => null,
                'created_at' => '2025-11-01',
                'updated_at' => '2025-11-01',
                'commission_amount' => 8
                /* 'insurances' => [2, 4],*/
            ],
            [
                'insurance_id' => 2,
                'booking_code' => 10000002,
                'first_name' => 'Alice',
                'last_name' => 'Smith',
                'birthday' => '1988-05-15',
                'email' => 'alice@example.com',
                'phone' => '+355222222222',
                'additional_phone' => null,
                'days' => 3,
                'daily_rate' => 20.00,
                'total_price' => 60.00,
                'addons_total' => 10.00,
                'pickup_date' => '2026-01-13',
                'dropoff_date' => '2026-01-14',
                'pickup_time' => '11:00:00',
                'dropoff_time' => '10:00:00',
                'ways_of_contact' => 2,
                'vehicle_id' => 1, // Golf
                'company_id' => 1,
                'pickup_location' => 1,
                'dropoff_location' => 2,
                'booking_status_id' => 4,
                'cancelled_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'commission_amount' => 12
                /*'insurances' => [1, 3],*/
            ],
            [
                'insurance_id' => 3,
                'booking_code' => 10000003,
                'first_name' => 'Michael',
                'last_name' => 'Johnson',
                'birthday' => '1985-03-22',
                'email' => 'michael@example.com',
                'phone' => '+355333333333',
                'additional_phone' => null,
                'days' => 2,
                'daily_rate' => 25.00,
                'total_price' => 50.00,
                'addons_total' => 5.00,
                'pickup_date' => '2026-01-13',
                'dropoff_date' => '2026-01-15',
                'pickup_time' => '08:00:00',
                'dropoff_time' => '20:00:00',
                'ways_of_contact' => 1,
                'vehicle_id' => 2, // Corolla
                'company_id' => 1,
                'pickup_location' => 2,
                'dropoff_location' => 2,
                'booking_status_id' => 3,
                'cancelled_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'commission_amount' => 10
                /*'insurances' => [3, 5],*/
            ],
            [
                'insurance_id' => 4,
                'booking_code' => 10000004,
                'first_name' => 'Sara',
                'last_name' => 'Williams',
                'birthday' => '1992-11-11',
                'email' => 'sara@example.com',
                'phone' => '+355444444444',
                'additional_phone' => null,
                'days' => 5,
                'daily_rate' => 25.00,
                'total_price' => 125.00,
                'addons_total' => 20.00,
                'pickup_date' => '2026-01-13',
                'dropoff_date' => '2026-01-16',
                'pickup_time' => '10:00:00',
                'dropoff_time' => '09:30:00',
                'ways_of_contact' => 3,
                'vehicle_id' => 2,
                'company_id' => 1,
                'pickup_location' => 1,
                'dropoff_location' => 1,
                'booking_status_id' => 3,
                'cancelled_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'commission_amount' => 25
                /* 'insurances' => [1, 3],*/
            ],
            [
                'insurance_id' => 5,
                'booking_code' => 10000005,
                'first_name' => 'David',
                'last_name' => 'Brown',
                'birthday' => '1980-07-19',
                'email' => 'david@example.com',
                'phone' => '+355555555555',
                'additional_phone' => null,
                'days' => 4,
                'daily_rate' => 65.00,
                'total_price' => 260.00,
                'addons_total' => 30.00,
                'pickup_date' => '2026-01-13',
                'dropoff_date' => '2026-01-23',
                'pickup_time' => '07:00:00',
                'dropoff_time' => '21:00:00',
                'ways_of_contact' => 1,
                'vehicle_id' => 3, // BMW X5
                'company_id' => 1,
                'pickup_location' => 3,
                'dropoff_location' => 3,
                'booking_status_id' => 3,
                'cancelled_at' => null,
                'created_at' => '2025-12-01',
                'updated_at' => '2025-12-01',
                'commission_amount' => 52
                /*'insurances' => [2, 5],*/
            ],
            [
                'insurance_id' => 1,
                'booking_code' => 10000006,
                'first_name' => 'Emma',
                'last_name' => 'Taylor',
                'birthday' => '1995-02-27',
                'email' => 'emma@example.com',
                'phone' => '+355666666666',
                'additional_phone' => null,
                'days' => 7,
                'daily_rate' => 65.00,
                'total_price' => 455.00,
                'addons_total' => 50.00,
                'pickup_date' => '2026-09-25',
                'dropoff_date' => '2026-10-01',
                'pickup_time' => '09:30:00',
                'dropoff_time' => '14:00:00',
                'ways_of_contact' => 2,
                'vehicle_id' => 3,
                'company_id' => 1,
                'pickup_location' => 2,
                'dropoff_location' => 1,
                'booking_status_id' => 5,
                'cancelled_at' => null,
                'created_at' => '2025-12-17',
                'updated_at' => '2025-12-17',
                'commission_amount' => 91
                /* 'insurances' => [1, 5],*/
            ],
            [
                'insurance_id' => 2,
                'booking_code' => 10000007,
                'first_name' => 'Robert',
                'last_name' => 'Anderson',
                'birthday' => '1987-06-30',
                'email' => 'robert@example.com',
                'phone' => '+355777777777',
                'additional_phone' => null,
                'days' => 2,
                'daily_rate' => 80.00,
                'total_price' => 160.00,
                'addons_total' => 15.00,
                'pickup_date' => '2026-10-05',
                'dropoff_date' => '2026-10-06',
                'pickup_time' => '12:00:00',
                'dropoff_time' => '11:00:00',
                'ways_of_contact' => 1,
                'vehicle_id' => 4, // Tesla
                'company_id' => 1,
                'pickup_location' => 1,
                'dropoff_location' => 3,
                'booking_status_id' => 5,
                'cancelled_at' => null,
                'created_at' => '2025-12-10',
                'updated_at' => '2025-12-10',
                'commission_amount' => 32
                /* 'insurances' => [2, 5],*/
            ],
            [
                'insurance_id' => 3,
                'booking_code' => 10000008,
                'first_name' => 'Sophia',
                'last_name' => 'Martinez',
                'birthday' => '1993-12-12',
                'email' => 'sophia@example.com',
                'phone' => '+355888888888',
                'additional_phone' => null,
                'days' => 5,
                'daily_rate' => 80.00,
                'total_price' => 400.00,
                'addons_total' => 25.00,
                'pickup_date' => '2026-10-10',
                'dropoff_date' => '2026-10-14',
                'pickup_time' => '10:30:00',
                'dropoff_time' => '15:00:00',
                'ways_of_contact' => 2,
                'vehicle_id' => 4,
                'company_id' => 1,
                'pickup_location' => 2,
                'dropoff_location' => 2,
                'booking_status_id' => 5,
                'cancelled_at' => null,
                'created_at' => '2025-11-29',
                'updated_at' => '2025-11-29',
                'commission_amount' => 80
                /*'insurances' => [1, 4]*/
            ],
            [
                'insurance_id' => 4,
                'booking_code' => 10000009,
                'first_name' => 'Daniel',
                'last_name' => 'Lee',
                'birthday' => '1991-04-04',
                'email' => 'daniel@example.com',
                'phone' => '+355999999999',
                'additional_phone' => null,
                'days' => 1,
                'daily_rate' => 25.00,
                'total_price' => 25.00,
                'addons_total' => 0.00,
                'pickup_date' => '2026-10-15',
                'dropoff_date' => '2026-10-15',
                'pickup_time' => '07:00:00',
                'dropoff_time' => '19:00:00',
                'ways_of_contact' => 3,
                'vehicle_id' => 2, // Corolla
                'company_id' => 1,
                'pickup_location' => 1,
                'dropoff_location' => 1,
                'booking_status_id' => 5,
                'cancelled_at' => null,
                'created_at' => '2025-12-05',
                'updated_at' => '2025-12-05',
                'commission_amount' => 5
                /*'insurances' => [3, 5]*/
            ],
            [
                'insurance_id' => 5,
                'booking_code' => 10000010,
                'first_name' => 'Olivia',
                'last_name' => 'Clark',
                'birthday' => '1994-09-09',
                'email' => 'olivia@example.com',
                'phone' => '+355101010101',
                'additional_phone' => null,
                'days' => 6,
                'daily_rate' => 20.00,
                'total_price' => 120.00,
                'addons_total' => 12.00,
                'pickup_date' => '2026-10-20',
                'dropoff_date' => '2026-10-25',
                'pickup_time' => '08:15:00',
                'dropoff_time' => '16:45:00',
                'ways_of_contact' => 2,
                'vehicle_id' => 1, // Golf
                'company_id' => 1,
                'pickup_location' => 3,
                'dropoff_location' => 3,
                'booking_status_id' => 5,
                'cancelled_at' => null,
                'created_at' => '2025-11-20',
                'updated_at' => '2025-11-20',
                'commission_amount' => 24
                /*  'insurances' => [1, 5],*/
            ],
            [
                    'insurance_id' => 3,
                    'booking_code' => 10000011,
                    'first_name' => 'Liam',
                    'last_name' => 'Harris',
                    'birthday' => '1992-08-18',
                    'email' => 'liam@example.com',
                    'phone' => '+355111222333',
                    'additional_phone' => null,
                    'days' => 3,
                    'daily_rate' => 50.00,
                    'total_price' => 150.00,
                    'addons_total' => 20.00,
                    'pickup_date' => '2026-11-01',
                    'dropoff_date' => '2026-11-04',
                    'pickup_time' => '09:00:00',
                    'dropoff_time' => '10:00:00',
                    'ways_of_contact' => 1,
                    'vehicle_id' => 3,
                    'company_id' => 1,
                    'pickup_location' => 2,
                    'dropoff_location' => 3,
                    'booking_status_id' => 4,
                    'cancelled_at' => null,
                    'created_at' => '2025-12-20',
                    'updated_at' => '2025-12-20',
                    'commission_amount' => 30
            ],

            [
                    'insurance_id' => 2,
                    'booking_code' => 10000012,
                    'first_name' => 'Mia',
                    'last_name' => 'Robinson',
                    'birthday' => '1996-03-05',
                    'email' => 'mia@example.com',
                    'phone' => '+355444555666',
                    'additional_phone' => null,
                    'days' => 2,
                    'daily_rate' => 70.00,
                    'total_price' => 140.00,
                    'addons_total' => 15.00,
                    'pickup_date' => '2026-11-05',
                    'dropoff_date' => '2026-11-07',
                    'pickup_time' => '11:00:00',
                    'dropoff_time' => '12:00:00',
                    'ways_of_contact' => 2,
                    'vehicle_id' => 4,
                    'company_id' => 1,
                    'pickup_location' => 1,
                    'dropoff_location' => 2,
                    'booking_status_id' => 5,
                    'cancelled_at' => null,
                    'created_at' =>'2025-12-25',
                    'updated_at' =>'2025-12-25',
                    'commission_amount' => 28
            ],
            [
                    'insurance_id' => 1,
                    'booking_code' => 10000013,
                    'first_name' => 'Ethan',
                    'last_name' => 'Walker',
                    'birthday' => '1989-12-22',
                    'email' => 'ethan@example.com',
                    'phone' => '+355777888999',
                    'additional_phone' => null,
                    'days' => 4,
                    'daily_rate' => 60.00,
                    'total_price' => 240.00,
                    'addons_total' => 25.00,
                    'pickup_date' => '2026-11-10',
                    'dropoff_date' => '2026-11-14',
                    'pickup_time' => '08:30:00',
                    'dropoff_time' => '09:30:00',
                    'ways_of_contact' => 1,
                    'vehicle_id' => 1,
                    'company_id' => 1,
                    'pickup_location' => 3,
                    'dropoff_location' => 1,
                    'booking_status_id' => 4,
                    'cancelled_at' => null,
                    'created_at' => '2027-03-10',
                    'updated_at' => '2027-03-10',
                    'commission_amount' => 48
            ],
            [
                'insurance_id' => 1,
                'booking_code' => 10000014,
                'first_name' => 'Ean',
                'last_name' => 'Paul',
                'birthday' => '1989-12-25',
                'email' => 'ethan@example.com',
                'phone' => '+355777888999',
                'additional_phone' => null,
                'days' => 4,
                'daily_rate' => 60.00,
                'total_price' => 240.00,
                'addons_total' => 25.00,
                'pickup_date' => '2026-11-10',
                'dropoff_date' => '2026-11-14',
                'pickup_time' => '08:30:00',
                'dropoff_time' => '09:30:00',
                'ways_of_contact' => 1,
                'vehicle_id' => 1,
                'company_id' => 1,
                'pickup_location' => 3,
                'dropoff_location' => 1,
                'booking_status_id' => 4,
                'cancelled_at' => null,
                'created_at' => '2027-03-12',
                'updated_at' => '2027-03-12',
                'commission_amount' => 48
            ],
            [
                'insurance_id' => 1,
                'booking_code' => 10000015,
                'first_name' => 'Ean',
                'last_name' => 'Paul',
                'birthday' => '1989-12-25',
                'email' => 'ethan@example.com',
                'phone' => '+355777888999',
                'additional_phone' => null,
                'days' => 4,
                'daily_rate' => 60.00,
                'total_price' => 240.00,
                'addons_total' => 25.00,
                'pickup_date' => '2026-11-10',
                'dropoff_date' => '2026-11-14',
                'pickup_time' => '08:30:00',
                'dropoff_time' => '09:30:00',
                'ways_of_contact' => 1,
                'vehicle_id' => 1,
                'company_id' => 1,
                'pickup_location' => 3,
                'dropoff_location' => 1,
                'booking_status_id' => 4,
                'cancelled_at' => null,
                'created_at' => '2027-03-11',
                'updated_at' => '2027-03-11',
                'commission_amount' => 48
            ],
            [
                'insurance_id' => 2,
                'booking_code' => 10000016,
                'first_name' => 'Ean',
                'last_name' => 'Paul',
                'birthday' => '1989-12-25',
                'email' => 'ethan@example.com',
                'phone' => '+355777888999',
                'additional_phone' => null,
                'days' => 5,
                'daily_rate' => 65.00,
                'total_price' => 325.00,
                'addons_total' => 25.00,
                'pickup_date' => '2026-11-10',
                'dropoff_date' => '2026-11-14',
                'pickup_time' => '08:30:00',
                'dropoff_time' => '09:30:00',
                'ways_of_contact' => 1,
                'vehicle_id' => 1,
                'company_id' => 1,
                'pickup_location' => 3,
                'dropoff_location' => 1,
                'booking_status_id' => 4,
                'cancelled_at' => null,
                'created_at' => '2027-04-11',
                'updated_at' => '2027-04-11',
                'commission_amount' => 50
            ],
            [
                'insurance_id' => 2,
                'booking_code' => 10000017,
                'first_name' => 'Ean',
                'last_name' => 'Paul',
                'birthday' => '1989-12-25',
                'email' => 'ethan@example.com',
                'phone' => '+355777888999',
                'additional_phone' => null,
                'days' => 5,
                'daily_rate' => 65.00,
                'total_price' => 325.00,
                'addons_total' => 25.00,
                'pickup_date' => '2026-11-10',
                'dropoff_date' => '2026-11-14',
                'pickup_time' => '08:30:00',
                'dropoff_time' => '09:30:00',
                'ways_of_contact' => 1,
                'vehicle_id' => 1,
                'company_id' => 1,
                'pickup_location' => 3,
                'dropoff_location' => 1,
                'booking_status_id' => 4,
                'cancelled_at' => null,
                'created_at' => '2025-11-25',
                'updated_at' => '2025-11-25',
                'commission_amount' => 50
            ],
            [
                'insurance_id' => 2,
                'booking_code' => 10000018,
                'first_name' => 'Ean',
                'last_name' => 'Paul',
                'birthday' => '1989-12-25',
                'email' => 'ethan@example.com',
                'phone' => '+355777888999',
                'additional_phone' => null,
                'days' => 5,
                'daily_rate' => 65.00,
                'total_price' => 325.00,
                'addons_total' => 25.00,
                'pickup_date' => '2026-11-10',
                'dropoff_date' => '2026-11-14',
                'pickup_time' => '08:30:00',
                'dropoff_time' => '09:30:00',
                'ways_of_contact' => 1,
                'vehicle_id' => 1,
                'company_id' => 1,
                'pickup_location' => 3,
                'dropoff_location' => 1,
                'booking_status_id' => 4,
                'cancelled_at' => null,
                'created_at' => '2025-11-11',
                'updated_at' => '2025-11-11',
                'commission_amount' => 50
            ],
            [
                'insurance_id' => 2,
                'booking_code' => 10000019,
                'first_name' => 'Ean',
                'last_name' => 'Paul',
                'birthday' => '1989-12-25',
                'email' => 'ethan@example.com',
                'phone' => '+355777888999',
                'additional_phone' => null,
                'days' => 5,
                'daily_rate' => 65.00,
                'total_price' => 325.00,
                'addons_total' => 25.00,
                'pickup_date' => '2026-11-10',
                'dropoff_date' => '2026-11-14',
                'pickup_time' => '08:30:00',
                'dropoff_time' => '09:30:00',
                'ways_of_contact' => 1,
                'vehicle_id' => 1,
                'company_id' => 1,
                'pickup_location' => 3,
                'dropoff_location' => 1,
                'booking_status_id' => 4,
                'cancelled_at' => null,
                'created_at' => '2025-12-11',
                'updated_at' => '2025-12-11',
                'commission_amount' => 50
            ],
            [
                'insurance_id' => 2,
                'booking_code' => 10000020,
                'first_name' => 'Eaner',
                'last_name' => 'Pauler',
                'birthday' => '1989-12-29',
                'email' => 'ethanol@example.com',
                'phone' => '+355777888999',
                'additional_phone' => null,
                'days' => 9,
                'daily_rate' => 85.00,
                'total_price' => 385.00,
                'addons_total' => 65.00,
                'pickup_date' => '2026-02-19',
                'dropoff_date' => '2026-02-19',
                'pickup_time' => '09:30:00',
                'dropoff_time' => '10:30:00',
                'ways_of_contact' => 2,
                'vehicle_id' => 2,
                'company_id' => 1,
                'pickup_location' => 5,
                'dropoff_location' => 6,
                'booking_status_id' => 4,
                'cancelled_at' => null,
                'created_at' => '2025-10-02',
                'updated_at' => '2025-10-05',
                'commission_amount' => 50
            ],

        ];

        foreach($bookings as $bookingData)
        {
            unset($bookingData['insurances']);

            $booking = Booking::create($bookingData);

            $booking->additionalServices()->attach([
                1 => ['quantity' => 1, 'price' => 10],
                3 => ['quantity' => 2, 'price' => 12],
            ]);
        }

    }
}


